### PR TITLE
Bug fixes and Enhancements

### PR DESCRIPTION
**Pull request by lionscribe**
1. Fixed setMenu function. Old version used to cause empty menu.
2. Removed mOriginalX variable, and using getLeft() in its place. mOriginalX got corrupted if onMeasure was called again.
3. Removed mMenu variable, as it is wrong to keep two matching arrays. In addition, the match was wrong, if a MenuItem was set as not visible. We now store the MenuItem in the View getTag().
4. Changed so that MenuItemID is used as the ViewID, in cases where the MenuItemID is set. This makes it easier to find MenuItems.
5. Added function setItemVisible(int itemID, boolean visible), which allows you to change MenuItem visibilty. This is useful for when Menu items have to change based on current view showing.
6. Added function addFabOnClickListener(OnClickListener listener)  to add an OnClickListener to the FAB, which is handled before the Menu is shown. This allows user to do changes in menu, based on current view.

### CODE REVIEW

**Comment by rubensousa** [comment]
Thanks. I'm going to try to check this out over the weekend.
I was going to try to refactor the way the menu is built and add a getMenu() method that allows further customization. Together with a notifyMenuChanged() or something, so that the FloatingToolbar would recreate the views.

**Comment by lionscribe** [comment]
Since I made the changes in an unknown-repository, I cannot figure out how to do further changes.
But based on your idea, I canged the onClick listener to the following;

`public interface OnFloatingToolbarListener
    {
        // Called before menu is shown. Don any changes you want to menu, including SetMenu. Return true to prevent menu from showing
        boolean handleShowFloatingMenu(FloatingToolbar toolbar);
    }

```
private OnFloatingToolbarListener mFloatingToolbarListener = null;
```

public void attachFab(FloatingActionButton fab) {
        mFab = fab;
        mFab.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mFloatingToolbarListener != null)
                {
                    if (mFloatingToolbarListener.handleShowFloatingMenu(FloatingToolbar.this))
                        return;
                }
                if (!mMorphed) {
                    show();
                }
            }
        });
    }

```
public void setFloatingToolbarListener(OnFloatingToolbarListener listener) {
    mFloatingToolbarListener = listener;
}
```

`

**Comment by lionscribe** [comment]
I also would add the isInEditMode() check, to prevent rendering issues in GUI
Like

`public FloatingToolbar(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        if (isInEditMode())
            return;
        TypedArray a = context.obtainStyledAttributes(attrs, R.styleable.FloatingToolbar, 0, 0);
`

**Comment by lionscribe** [comment]
I have just forked this repository, and committed all my fixes and changes, and have now create a new pull request that encompasses it all.

**Pull request closed without merging**
