### PR TITLE
Many changes and improvements

### PR DESCRIPTION
**Pull request by lionscribe**
- Can now be used on Pre Icecream devices, albeit without animations.
- Added OnFloatingToolbarListener interface, which you set via setFloatingToolbarListener, which gets called before menu is shown, so that menu can be customized based on current view.
- Fixed setMenu function. Old version used to cause empty menu.
- Removed mOriginalX variable, and using getLeft() in its place. mOriginalX got corrupted if onMeasure was called again.
- Removed mMenu variable, as it is wrong to keep two matching arrays. In addition, the match was wrong, if a MenuItem was set as not visible. \* \* We now store the MenuItem in the View getTag().
- Changed so that MenuItemID is used as the ViewID, in cases where the MenuItemID is set. This makes it easier to find MenuItems.
- Added function setItemVisible(int itemID, boolean visible), which allows you to change MenuItem visibilty. This is useful for when Menu items have to change based on current view showing.
- Added the isInEditMode() check, to prevent rendering issues in GUI
- Changed to use addOnLayoutChangeListener rather than globalLayoutListener
- Moved measuring of mFab from onMeasure to a listener. Sometimes onMeasure was called before mFab was measured.
- Many other bug fixes and improvements

### CODE REVIEW

**Comment by rubensousa** [comment]
Hi, thanks for making a new pull request that includes all the changes.

I'm just against these:
1. Backport to API 9. I want to keep the minimum API as 14.
2. You've added a check for isInEditMode() that makes the xml preview not show the menu items.

Like I told in you in the other pull request, I prefer keeping the mMenu member variable and add a method to notify menu changes.
Can you revert back the changes above? If not, I'll merge this and take care of it later.

**Comment by lionscribe** [comment]
1. Why would you be upset about the backport? You were anyways using ViewCompat, This way you are allowing users to use it, even when they are supporting API 9. (For example, my project).
2. The correct way is that isInEditMode should just show a blank menu (when wanted). Not sure how to implement it. Without isInEditMode it throws an error when rendering.
3. The problem with the mMenu variable is that it was very unsafe and unprofessional to match by array index. For example, if one menu item was marked as hidden, it was not added to the view, so now the view index does not match the menu index. There is no reason to hold on to the mMenu variable, and my way of  holding the individual MenuItem in the Tag, is much safer and cleaner.

Either way it's your call, as I have done all the changes for my use, and am just passing it back to you in appreciation of your releasing it.
Good Luck!

**Comment by rubensousa** [comment]
1. I wouldn't be upset. It's just that it's kind of pointless to keep supporting older version when most users are already at 15 or above. Take it as a force to update action.
2. Why would you want to see a blank menu? We can do this with a custom attribute. Something like previewMenu or something, that defaults to true.
3. I was matching by index since at the beginning I wasn't supporting hidden items. I agree that I need to change that, but the idea of keeping the variable is that you can change it directly, after using getMenu() and then calling notifyMenuChanged() so that the toolbar redraws the views accordingly.

Thanks for the contribution.

**Comment by lionscribe** [comment]
1. You are correct, but I would rather not estrange users, when I can support them minimally.
2. I meant a preview menu, with just an outline, so that you can see through it. Sorry for that. The custom attribute is a good idea, but may be complicated for user.
3. Sounds like a good idea. You can do both. Save the mMenu for future changes, and save the MenuItems in the TAG, so that there is no need to compare index.
   Good Luck!

**Comment by rubensousa** [comment]
3 -> Yes, I'll do both. The menu items in the tag will be used for the click listener :)

**Pull request merged**
