### PR TITLE
Update FloatingToolbar.java

### PR DESCRIPTION
**Pull request by lionscribe**
- Completely removed the variables
  mFabOriginalX, mFabOriginalY, mFabNewY
  as holding them caused issues.
  We now get the values on the fly, we just hold on to the new variable mVerticalOffset and it to the computation
- Added following  functions:
  public void setItemSelected(int itemID, boolean selected)
  public MenuItem findMenuItem(int itemID)

### CODE REVIEW

**Comment by rubensousa** [comment]
1. What issues did it cause?
2. Why do you need to select a view? I think I prefer a general method: getMenuView(int itemId).

Since you've added a pull request to a old version of the develop branch, I won't be able to merge. But I'll test the first change.

**Comment by lionscribe** [comment]
1. Issue was that when I had the activity resize when keyboard was shown,
   which causes the fab to move with keyboard, then after menu is shown, fab
   was returned to wrong place (as fab had moved from when we originally saved
   it). The same thing could happen when users handles orientation changes
   themselves. I also had an issue, when I setup floating toolbar, to be
   iniddle of activity, not bottom. The change I did solved it.
2. I had to select a view when I used the menu for selecting a sort order,
   and to show which one is selected. (I still have to fix the style, as it
   makes it very light.) Your idea of a general getMenuItem sounds very good.

**Comment by rubensousa** [comment]
1. It makes sense then. The original values would be pointless in this case.
2. It would be getMenuView. You should use this later to get the menu's view.

Thanks once again! I'll review these changes in the last develop branch. If want, you could send a new pull request against the latest commit with getMenuView instead of those 2 methods you've added.

**Comment by lionscribe** [comment]
Sorry, I  have been very busy lately.

2 small issues, if you can maybe resolve.
1. ```
     When I set a menu item as selected, the image becomes very faint, and barely visible. Sometimes, it’s completely invisible. I tried setting the backgrounddrawable and many other tricks, but couldn’t solve.
   ```
2. ```
     In one application, I used a mini floating button, and have the floating toolbar on the same line (not below). It works nice, but when it closes it makes a small arc, which I am trying to remove. This is the setup
   ```

<com.github.rubensousa.floatingtoolbar.FloatingToolbar
    android:id="@+id/floatingToolbar"
    android:layout_width="match_parent"
    android:layout_height="?attr/actionBarSize"
    android:layout_marginTop="?attr/actionBarSize"
    android:layout_gravity="center_vertical|right|end"
    app:floatingMenu="@menu/menu_home_list_floating"/>

<android.support.design.widget.FloatingActionButton
    android:id="@+id/fab"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginTop="?attr/actionBarSize"
    android:layout_gravity="center_vertical|right|end"
    android:layout_marginRight="8dp"
    android:layout_marginLeft="8dp"
    app:fabSize="mini"
    app:srcCompat="@drawable/ic_menu"/>

Thank you,

Lionscribe

**Comment by rubensousa** [comment]
1. Why are you marking a menu item as selected?
2. I'll take a look at this when I have more time.

**Comment by lionscribe** [comment]
I am using the menu as an option to select the sort order. One order is the
current order, so we want it shown as selected.
I think have figured out the issue, but have no solution so far. Android
seems to highlight the selected option with the accent color. As we are
using the accent as the background color, therefore the selected looks
invisible.
I will try working on it, using a different background.

On Jul 18, 2016 10:17 AM, "Rúben Sousa" notifications@github.com wrote:

   1.

   Why are you marking a menu item as selected?
   2.

   I'll take a look at this when I have more time.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/rubensousa/FloatingToolbar/pull/15#issuecomment-233341625,
or mute the thread

**Comment by rubensousa** [comment]
This is why I've added the option to set a custom view. This way, you can customize the behavior yourself. 
The menu option is just meant to support the basic click event. Every other action you want to do should be made with a custom view.

**Comment by lionscribe** [comment]
Thanks

**Comment by rubensousa** [comment]
Can you please check out the latest develop branch? I've added some of your suggestions. I'll be releasing 1.0.1 soon if everything is ok.

**Comment by lionscribe** [comment]
Sorry, I just got back today. I see you committed already. Looks much cleaner. I already handed over that project, but will look out in the future.

Good Luck!

**Comment by rubensousa** [comment]
Ok, I'm going to close this then. I'll release an update tomorrow after a couple of more tests

**Pull request closed without merging**
